main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main')
]

stockAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include
import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
import uuid

# Create your models here.


class Indicators (models.Model):
    INTERVALS = (
        ('1m', '1 minute'),
        ('2m', '2 minute'),
        ('5m', '5 minute'),
        ('15m', '15 minute'),
        ('30m', '30 minute'),
        ('60m', '60 minute'),
        ('90m', '90 minute'),
        ('1h', '1 hour'),
        ('1d', '1 day'),
        ('5d', '5 day'),
        ('1wk', '1 week'),
        ('1mo', '1 month'),
        ('3mo', '3 month'),
    )
    PERIODS = (
        ('1d', '1 day'),
        ('5d', '5 day'),
        ('1mo', '1 month'),
        ('3mo', '3 month'),
        ('6mo', '6 month'),
        ('1y', '1 year'),
        ('2y', '2 year'),
        ('5y', '5 year'),
        ('10y', '10 year'),
        ('ytd', 'year-to-date'),
        ('max', 'Max'),
    )
    CHARTS = (
        ('candlestick', 'Candlestick'),
        ('ohlc', 'OHLC'),
    )
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=True)
    interval = models.CharField(max_length=200, choices=INTERVALS, default='1m')
    period = models.CharField(max_length=200, choices=PERIODS)
    type = models.CharField(max_length=200, choices=CHARTS)
    rsi = models.BooleanField(default=False)
    macd = models.BooleanField(default=False)

main/forms.py
from django import forms

INTERVALS = (
    ('1m', '1 minute'),
    ('2m', '2 minute'),
    ('5m', '5 minute'),
    ('15m', '15 minute'),
    ('30m', '30 minute'),
    ('1h', '1 hour'),
    ('1d', '1 day'),
    ('5d', '5 day'),
    ('1wk', '1 week'),
    ('1mo', '1 month'),
    ('3mo', '3 month'),
)

PERIODS = (
    ('1d', '1 day'),
    ('5d', '5 day'),
    ('1mo', '1 month'),
    ('3mo', '3 month'),
    ('6mo', '6 month'),
    ('1y', '1 year'),
    ('2y', '2 year'),
    ('5y', '5 year'),
    ('10y', '10 year'),
    ('ytd', 'year-to-date'),
    ('max', 'Max'),
)
CHARTS = (
    ('Candlestick', 'Candlestick'),
    ('OHLC', 'OHLC'),
)

EQUITY_NAMES = (('ADANIPORTS.NS', 'Adani Ports and Special Economic Zone Ltd.'), ('ASIANPAINT.NS', 'Asian Paints Ltd.'), ('AXISBANK.NS', 'Axis Bank Ltd.'), ('BAJAJ-AUTO.NS', 'Bajaj Auto Ltd.'), ('BAJFINANCE.NS', 'Bajaj Finance Ltd.'), ('BAJAJFINSV.NS', 'Bajaj Finserv Ltd.'), ('BPCL.NS', 'Bharat Petroleum Corporation Ltd.'), ('BHARTIARTL.NS', 'Bharti Airtel Ltd.'), ('BRITANNIA.NS', 'Britannia Industries Ltd.'), ('CIPLA.NS', 'Cipla Ltd.'), ('COALINDIA.NS', 'Coal India Ltd.'), ('DIVISLAB.NS', "Divi's Laboratories Ltd."), ('DRREDDY.NS', "Dr. Reddy's Laboratories Ltd."), ('EICHERMOT.NS', 'Eicher Motors Ltd.'), ('GRASIM.NS', 'Grasim Industries Ltd.'), ('HCLTECH.NS', 'HCL Technologies Ltd.'), ('HDFCBANK.NS', 'HDFC Bank Ltd.'), ('HDFCLIFE.NS', 'HDFC Life Insurance Company Ltd.'), ('HEROMOTOCO.NS', 'Hero MotoCorp Ltd.'), ('HINDALCO.NS', 'Hindalco Industries Ltd.'), ('HINDUNILVR.NS', 'Hindustan Unilever Ltd.'), ('HDFC.NS', 'Housing Development Finance Corporation Ltd.'), ('ICICIBANK.NS', 'ICICI Bank Ltd.'), ('ITC.NS', 'ITC Ltd.'), ('IOC.NS',
                'Indian Oil Corporation Ltd.'), ('INDUSINDBK.NS', 'IndusInd Bank Ltd.'), ('INFY.NS', 'Infosys Ltd.'), ('JSWSTEEL.NS', 'JSW Steel Ltd.'), ('KOTAKBANK.NS', 'Kotak Mahindra Bank Ltd.'), ('LT.NS', 'Larsen & Toubro Ltd.'), ('M&M.NS', 'Mahindra & Mahindra Ltd.'), ('MARUTI.NS', 'Maruti Suzuki India Ltd.'), ('NTPC.NS', 'NTPC Ltd.'), ('NESTLEIND.NS', 'Nestle India Ltd.'), ('ONGC.NS', 'Oil & Natural Gas Corporation Ltd.'), ('POWERGRID.NS', 'Power Grid Corporation of India Ltd.'), ('RELIANCE.NS', 'Reliance Industries Ltd.'), ('SBILIFE.NS', 'SBI Life Insurance Company Ltd.'), ('SHREECEM.NS', 'Shree Cement Ltd.'), ('SBIN.NS', 'State Bank of India'), ('SUNPHARMA.NS', 'Sun Pharmaceutical Industries Ltd.'), ('TCS.NS', 'Tata Consultancy Services Ltd.'), ('TATACONSUM.NS', 'Tata Consumer Products Ltd.'), ('TATAMOTORS.NS', 'Tata Motors Ltd.'), ('TATASTEEL.NS', 'Tata Steel Ltd.'), ('TECHM.NS', 'Tech Mahindra Ltd.'), ('TITAN.NS', 'Titan Company Ltd.'), ('UPL.NS', 'UPL Ltd.'), ('ULTRACEMCO.NS', 'UltraTech Cement Ltd.'), ('WIPRO.NS', 'Wipro Ltd.'))

MA_TYPES = (
    ('SMA', 'Simple'),
    ('EMA', 'Exponential'),
)

MA_VALUES = (
    ('Open', 'Open'),
    ('High', 'High'),
    ('Low', 'Low'),
    ('Close', 'Close'),
)


class MainForm(forms.Form):

    equityName = forms.ChoiceField(
        choices=EQUITY_NAMES, widget=forms.Select(attrs={'class': 'custom-select'}), label='Equity Name', required=True, initial=EQUITY_NAMES[0][0]
    )

    interval = forms.ChoiceField(
        choices=INTERVALS, widget=forms.Select(attrs={'class': 'custom-select'}), label='Interval', required=True, initial=INTERVALS[0][0]
    )

    period = forms.ChoiceField(
        choices=PERIODS, widget=forms.Select(attrs={'class': 'custom-select'}), label='Period', required=True, initial=PERIODS[0][0])

    chartType = forms.ChoiceField(
        choices=CHARTS, widget=forms.Select(attrs={'class': 'custom-select'}), label='Chart', required=True, initial=CHARTS[0][0])

    rsiStatus = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input'}),
        required=False, label='RSI: Relative Strength Index', initial=False)
    macdStatus = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input'}),
        required=False, label='MACD: Moving Average Convergence Divergence', initial=False)

    ma1Status = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input'}), required=False, label='MA1: Moving Average', initial=False)
    ma2Status = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'custom-control-input'}),
        required=False, label='MA2: Moving Average', initial=False)

    rsiParameter = forms.IntegerField(
        required=False, min_value=1, max_value=100, label='RSI Parameter',
        initial='14', widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    macdParameters = forms.CharField(
        required=False, label='MACD Parameter',
        initial='12, 26, 9', widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    ma1Period = forms.IntegerField(
        required=False, min_value=1, max_value=100,
        initial='20', widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    ma1Type = forms.ChoiceField(
        choices=MA_TYPES, widget=forms.Select(attrs={'class': 'custom-select'}), required=False, initial=MA_TYPES[0][0]
    )

    ma1Parameter = forms.ChoiceField(
        choices=MA_VALUES, widget=forms.Select(attrs={'class': 'custom-select'}), required=False, initial=MA_VALUES[0][0]
    )

    ma2Period = forms.IntegerField(
        required=False, min_value=1, max_value=100,
        initial='50', widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    ma2Type = forms.ChoiceField(
        choices=MA_TYPES, widget=forms.Select(attrs={'class': 'custom-select'}), required=False, initial=MA_TYPES[0][0]
    )

    ma2Parameter = forms.ChoiceField(
        choices=MA_VALUES, widget=forms.Select(attrs={'class': 'custom-select'}), required=False, initial=MA_VALUES[0][0]
    )

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
import numpy as np
from . import forms
import plotly.graph_objects as go
from plotly.offline import plot
import yfinance as yf
from plotly.subplots import make_subplots


def calculateMA(df, period, type, parameter):
    if type == 'SMA':
        df['MA'] = df[parameter].rolling(
            window=period, min_periods=period).mean()
    elif type == 'EMA':
        df['MA'] = df[parameter].ewm(span=period, adjust=False).mean()
    return df


def calculateRsi(df, period):
    delta = df['Close'].diff()
    up = delta.clip(lower=0)
    down = -1*delta.clip(upper=0)
    ema_up = up.ewm(com=period, adjust=False).mean()
    ema_down = down.ewm(com=period, adjust=False).mean()
    rs = ema_up/ema_down
    df['RSI'] = 100 - (100/(1 + rs))

    return df


def calculateMACD(df, paramters):
    df['k'] = df['Close'].ewm(
        span=paramters[0], adjust=False, min_periods=paramters[0]).mean()
    df['d'] = df['Close'].ewm(
        span=paramters[1], adjust=False,  min_periods=paramters[1]).mean()
    df['MACD'] = df['d'] - df['k']
    df['Signal'] = df['MACD'].ewm(
        span=paramters[2], adjust=False, min_periods=paramters[1]).mean()
    df['Hist'] = df['MACD'] - df['Signal']
    return df


def generateTable(df, period):
    df = calculateRsi(df, period)
    df['date'] = df.index.date.astype(str)
    dfGroup = df.groupby(['date']).agg({
        'Close': ['mean', 'std', lambda x: x.iloc[0], lambda x: x.iloc[-1]],
        'RSI': ['mean'],
    }).round(2)
    dfGroup.columns = [x[1] for x in dfGroup.columns]
    dfGroup = dfGroup.reset_index()
    dfGroup.columns = ['Date', 'Mean Price',
                       'STD Price', 'Start', 'End', 'RSI Mean']
    dfGroup['Net Change'] = (dfGroup['Start'] - dfGroup['End']).round(2)
    dfGroup = dfGroup[['Date', 'Mean Price', 'STD Price',
                       'RSI Mean', 'Start', 'End', 'Net Change']]
    return dfGroup


def updateChart(form):
    plotCount = 2

    if form is None:
        form = forms.MainForm()
        print('Form is none')
        ticker = form.fields['equityName'].initial
        interval = form.fields['interval'].initial
        period = form.fields['period'].initial
        chartType = form.fields['chartType'].initial
        rsiStatus = form.fields['rsiStatus'].initial
        macdStatus = form.fields['macdStatus'].initial
        ma1Status = form.fields['ma1Status'].initial
        ma2Status = form.fields['ma2Status'].initial

    else:
        print('Form is not none')
        ticker = form.cleaned_data['equityName']
        interval = form.cleaned_data['interval']
        period = form.cleaned_data['period']
        chartType = form.cleaned_data['chartType']
        rsiStatus = form.cleaned_data['rsiStatus']
        macdStatus = form.cleaned_data['macdStatus']
        ma1Status = form.cleaned_data['ma1Status']
        ma2Status = form.cleaned_data['ma2Status']
        rsiParameter = form.cleaned_data['rsiParameter']
        macdParameters = form.cleaned_data['macdParameters']
        ma1Parameter = form.cleaned_data['ma1Parameter']
        ma1Type = form.cleaned_data['ma1Type']
        ma1Period = form.cleaned_data['ma1Period']
        ma2Parameter = form.cleaned_data['ma2Parameter']
        ma2Type = form.cleaned_data['ma2Type']
        ma2Period = form.cleaned_data['ma2Period']

    # Get the data from yfinance
    df = yf.download(ticker, interval=interval, period=period)

    # Define default parameters for chart
    specs = [[{}], [{}]]
    rowHeights = [2.0, 0.3]
    subplotTitles = [chartType, 'Volume']

    # Check if the user wants to see the RSI
    if(rsiStatus):
        # Increase plot count by 2
        plotCount += 2

        # Calculate the RSI
        df = calculateRsi(df, period=int(rsiParameter))
        # Calculate the table
        df_group = generateTable(df, period=int(rsiParameter))

        # Add the values for the RSI to the parameters
        specs.extend([[{}], [{"type": "table"}]])
        rowHeights.extend([0.3, 0.3])
        subplotTitles.extend(['RSI', ''])

    # Check if the user wants to see the MACD
    if(macdStatus):
        # Increase plot count by 1
        plotCount += 1

        # Calculate the MACD
        df = calculateMACD(df, [int(x) for x in macdParameters.split(',')])

        # Add the values for the MACD to the parameters
        rowHeights.append(0.3)
        if not rsiStatus:
            specs.append([{}])
            subplotTitles.append('MACD')
        else:
            specs.insert(-1, [{}])
            subplotTitles.insert(-1, 'MACD')

    # Create subplots for the chart
    fig = go.Figure(make_subplots(
        rows=plotCount, cols=1, shared_xaxes=True,
        vertical_spacing=0.06,
        specs=specs,
        row_heights=rowHeights,
        subplot_titles=subplotTitles
    ))

    chartName = dict(form.fields['equityName'].choices)[
        ticker] + ' ' + chartType
    # Add the Candlestick or OHLC chart to the figure
    if chartType == 'Candlestick':
        fig.add_trace(
            go.Candlestick(
                x=df.index, open=df['Open'], high=df['High'],
                low=df['Low'], close=df['Close'], name=chartName,
                increasing_line_color='rgb(27,158,119)', decreasing_line_color='rgb(204,80,62)'
            ), row=1, col=1,

        )
    elif chartType == 'OHLC':
        fig.add_trace(
            go.Ohlc(
                x=df.index, open=df['Open'], high=df['High'],
                low=df['Low'], close=df['Close'], name=chartName,
                increasing_line_color='rgb(27,158,119)', decreasing_line_color='rgb(204,80,62)'
            ), row=1, col=1,
        )

    # Add the Volume chart to the figure
    fig.add_trace(
        go.Bar(
            x=df.index, y=df['Volume'],
            marker_color='orange', showlegend=False),
        row=2, col=1
    )

    # Check if user wants to see Moving Average 1
    if(ma1Status):
        # Calculate the Moving Average 1
        df = calculateMA(df, period=int(ma1Period),
                         parameter=ma1Parameter, type=ma1Type)

        # Add the Moving Average 1 chart to the figure
        fig.add_trace(
            go.Scatter(
                x=df.index, y=df['MA'], name='Moving Avg(1)'),
            row=1, col=1
        )

    # Check if user wants to see Moving Average 2
    if(ma2Status):
        # Calculate the Moving Average 2
        df = calculateMA(df, period=int(ma2Period),
                         parameter=ma2Parameter, type=ma2Type)
        # Add the Moving Average 2 chart to the figure
        fig.add_trace(
            go.Scatter(
                x=df.index, y=df['MA'], name='Moving Avg(2)'),
            row=1, col=1
        )

    # Check if user wants to see RSI
    if rsiStatus:
        # Find the row index for the RSI plot
        rowIndex = plotCount - 2 if macdStatus else plotCount - 1

        # Add the RSI plot to the figure
        fig.add_trace(
            go.Scatter(
                x=df.index, y=df['RSI'],
                name='RSI', marker_color='#109618'
            ), row=rowIndex, col=1,
        )

        # Add the plot for the overbought and oversold lines
        fig.add_trace(
            go.Scatter(
                x=df.index, y=[70] * len(df.index),
                name='Overbought', marker_color='#109618',
                line=dict(dash='dot'),
            ), row=rowIndex, col=1,
        )
        fig.add_trace(
            go.Scatter(
                x=df.index, y=[30] * len(df.index),
                name='Oversold', marker_color='#109610',
                line=dict(dash='dot'),
            ), row=rowIndex, col=1,
        )

        # Add the Table to the figure
        fig.add_trace(
            go.Table(
                header=dict(
                    values=list(df_group.columns),
                    fill_color='#C2D4FF',
                    font=dict(size=10), align="left"),
                cells=dict(
                    fill_color='#F5F8FF',
                    values=[df_group[k].tolist() for k in df_group.columns[0:]], align="left")
            ), row=plotCount, col=1
        )

    # Check if user wants to see MACD
    if macdStatus:
        # Find the row index for the MACD plot
        rowIndex = plotCount - 1 if rsiStatus else plotCount

        # Add the MACD plot to the figure
        fig.add_trace(
            go.Scatter(
                x=df.index, y=df['MACD'],
                name='MACD', marker_color='#ff9900'
            ), row=rowIndex, col=1,
        )

        # Add the MACD Signal plot to the figure
        fig.add_trace(
            go.Scatter(
                x=df.index, y=df['Signal'],
                name='Signal', marker_color='#000000',
                line=dict(dash='dot'),
            ), row=rowIndex, col=1,
        )

        # Calculate colors based on the MACD histogram values
        colors = np.where(df['Hist'] < 0, '#000', '#ff9900')

        # Add the MACD Histogram plot to the figure
        fig.append_trace(
            go.Bar(
                x=df.index,
                y=df['Hist'],
                name='Histogram',
                marker_color=colors,
            ), row=rowIndex, col=1
        )

    # Update the X-axis values based on values of interval
    # fig.update_xaxes(
    #     rangebreaks=[
    #         dict(bounds=[16, 9], pattern="hour"),
    #         dict(bounds=["sat", "mon"]),
    #     ]
    # )

    # Update the layout
    fig.update_layout(
        title=dict(form.fields['equityName'].choices)[ticker] + ' Report',
        xaxis={
            'rangeslider': {'visible': False},
            'type': 'date'
        },
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        ),
        height=1300 if plotCount > 2 else 800,
        width=1500,
    )

    # Return the figure
    return plot(fig, output_type='div')


def main(request):

main/templates/main/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <script src="https://cdn.plot.ly/plotly.latest.min.js"></script>

    <title>Stock Market Analysis</title>

    <script>
        function isFormValid() {
            const interval = document.getElementsByName("interval")[0].value;
            const period = document.getElementsByName("period")[0].value;
            const macdStatus = document.getElementsByName("macdStatus")[0].checked;
            const macdParameters = document.getElementsByName("macdParameters")[0].value;
            const rsiStatus = document.getElementsByName("rsiStatus")[0].checked;
            const rsiParameter = document.getElementsByName("rsiParameter")[0].value;
            const ma1Status = document.getElementsByName("ma1Status")[0].checked;
            const ma1Period = document.getElementsByName("ma1Period")[0].value;
            const ma2Status = document.getElementsByName("ma2Status")[0].checked;
            const ma2Period = document.getElementsByName("ma2Period")[0].value;

            if (period != "1d" && period != "5d") {

                if (interval == "1m" || interval == "2m" || interval == "5m" || interval == "15m" || interval == "30m" || interval == "1h") {
                    alert(" Only 5 days worth of intraday granularity data are allowed.")
                    return false;
                }
            }

            if (macdStatus) {
                if (macdParameters == "") {
                    alert("Please enter MACD parameters.");
                    return false;
                } else if (macdParameters.split(",").length != 3) {
                    alert("Please enter 3 MACD parameters.");
                    return false;
                } else {
                    var macdParametersArray = macdParameters.split(",");
                    for (var i = 0; i < 3; i++) {
                        if (isNaN(parseInt(macdParametersArray[i]))) {
                            alert("Please enter valid MACD parameters.");
                            return false;
                        }
                    }
                }
            }

            if (rsiStatus) {
                if (rsiParameter == "") {
                    alert("Please enter RSI parameters.");
                    return false;
                }
            }

            if (ma1Status) {
                if (ma1Period == "") {
                    alert("Please enter MA1 parameters.");
                    return false;
                }
            }

            if (ma2Status) {
                if (ma2Period == "") {
                    alert("Please enter MA2 parameters.");
                    return false;
                }
            }
            
        }
    </script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <h2> <a class="navbar-brand" href="#">Stock Analysis</a></h2>
        </nav>
    </header>

    <main>
        <div class="container-fluid py-3">
            <form method="post">
                {% csrf_token %}
                <div class="row px-3">
                    <div class="card-deck">
                        <div class="card shadow">
                            <div class="card-header rounded-top bg-info text-white">
                                <h5 class="mb-0 card-title">{{title}}</h5>
                            </div>
                            <div class="card-body px-4 py-2">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            {{form.equityName.label}}
                                            {{form.equityName}}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            {{form.interval.label}}
                                            {{form.interval}}
                                        </div>
                                        <div class="form-group">
                                            {{form.period.label}}
                                            {{form.period}}
                                        </div>
                                        <div class="form-group">
                                            {{form.chartType.label}}
                                            {{form.chartType}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card shadow">
                            <div class="card-header rounded-top bg-info text-white">
                                <h5 class="mb-0 card-title">Indicators</h5>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="custom-control custom-switch">
                                                    {{form.rsiStatus}}
                                                    <label class="custom-control-label" for="id_rsiStatus">
                                                        {{form.rsiStatus.label}}</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    {{form.rsiParameter.label}}
                                                    {{form.rsiParameter}}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="custom-control custom-switch">
                                                    {{form.macdStatus}}
                                                    <label class="custom-control-label" for="id_macdStatus">
                                                        {{form.macdStatus.label}}</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    {{form.macdParameters.label}}
                                                    {{form.macdParameters}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="custom-control custom-switch">
                                                    {{form.ma1Status}}
                                                    <label class="custom-control-label" for="id_ma1Status">
                                                        {{form.ma1Status.label}}</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4 py-2">
                                                <div class="form-group">
                                                    {{form.ma1Parameter}}
                                                </div>
                                            </div>
                                            <div class="col-md-5 py-2">
                                                <div class="form-group">
                                                    {{form.ma1Type}}
                                                </div>
                                            </div>
                                            <div class="col-md-3 py-2">
                                                <div class="form-group">
                                                    {{form.ma1Period}}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="custom-control custom-switch">
                                                    {{form.ma2Status}}
                                                    <label class="custom-control-label" for="id_ma2Status">
                                                        {{form.ma2Status.label}}</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4 py-2">
                                                <div class="form-group">
                                                    {{form.ma2Parameter}}
                                                </div>
                                            </div>
                                            <div class="col-md-5 py-2">
                                                <div class="form-group">
                                                    {{form.ma2Type}}
                                                </div>
                                            </div>
                                            <div class="col-md-3 py-2">
                                                <div class="form-group">
                                                    {{form.ma2Period}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row px-4 py-3">
                    <div class="col-md-12">
                        <input type="submit" onclick="return isFormValid();" class="btn btn-info w-100 shadow"
                            value="Update Chart">
                    </div>
                </div>
            </form>
            <div class="row overflow-auto">
                {{chart | safe}}
            </div>
        </div>

    </main>

    <script src="https://cdn.plot.ly/plotly.latest.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>

</html>